### PR TITLE
REF: Split templates between core and devices

### LINKED ISSUE #336: Typhos-provided screens not considered "device-specific" screens
* `PositionerBase.*.ui` is provided with typhos, but will not be recommended over `detailed_tree.ui`
* The check is something like: "do we have specific (* not typhos-provided) screens for this class? Is the device complicated enough to suggest a tree?"

Possible solution
------------------
Provide two `.ui` file areas: 
1. `typhos.ui.core` for core templates that have nothing to do with classes
2. `typhos.ui.device` for ophyd-wide device classes (such as `PositionerBase`)
The former would be considered "typhos provided" in the current methodology and the latter would be considered "device-specific"

### PR DESCRIPTION
**Pull request by hhslepicka**
## Description
This PR separates the ui templates into `core`, `devices` and `widgets`.

- `core` should contain the templates that are internal to Typhos for autogenerated screens (detailed_tree, engineering, etc).
- `devices` should contain at least for now templates tailored for specific devices class.
- `widgets` should contain UI files related to Widgets provided by Typhos such as `tweakable`, `positioner`, etc

In order to keep the changes relatively small more work will come at other PRs to address the following somewhat related issues:
- https://github.com/pcdshub/typhos/issues/311
- https://github.com/pcdshub/typhos/issues/359
- https://github.com/pcdshub/typhos/issues/342

## Motivation and Context
Closes #336 

## How Has This Been Tested?
All tests are passing (at least locally).

## Where Has This Been Documented?
N/A

## Screenshots (if appropriate):
Screen generated by: `typhos --fake-device pcdsdevices.pim.PPM['{"prefix":"fooo","name":"PPM_Test"}']`

- with master:
Screen Shot 2020-07-23 at 9 46 25 AM

- with this PR:
Screen Shot 2020-07-23 at 9 45 20 AM

### CODE REVIEW

**Comment by ZLLentz** [comment]
I guess there is another problem here in your screenshot where the positioner screen breaks for state positioners (see #339)

**Comment by hhslepicka** [comment]
Working with this branch a bit more after talking with Zach and trying to get a closure also for #339 here.
With the latest changes of this PR we can now see the Positioner and StatePositioner both using the TyphosPositionerWidget to render the screen.
Screen Shot 2020-07-28 at 5 08 50 PM

I still need to test this solution more with a real device but adding this up here to gather input on whether this is a good idea or not.

TODO
------
- [ ] Test with a real device moving it around
- [ ] Add also the StatePositioner.embedded template.

**Comment by klauer** [comment]
Seems reasonable 👍

**Comment by hhslepicka** [comment]
I just tested the new positioner with `im1k1` and issues were fixed.
image

**Comment by hhslepicka** [comment]
This PR is ready for a new round of reviews. @klauer and @ZLLentz 
The only 🐘 in the room is the `Stop` button which we have no clear way to find out programmatically if we need or not to remove it since the method `stop` is implemented at the `PositionerBase`.

**Comment by klauer** [comment]
If it works for both positioner types, I'd say merge at will. 👍

**Comment by ZLLentz** [comment]
Later we will rework `StatePositioner` to not have a `stop` method at all (since there is no real reason it needs to subclass `Positioner`, aside from some refactoring)

**Pull request merged**
