### PR TITLE
REF/CLEAN: Remove typhon

### PR DESCRIPTION
**Pull request by klauer**
Typhon will not live to see the shelter-in-place.
Long live Typhos!

### CODE REVIEW

**Comment by klauer** [comment]
And here we go with CI... let's see how many tries this takes...

**Comment by hhslepicka** [comment]
I bet 5 for CI

**Comment by klauer** [comment]
If I get to 6 I'll rebase and force-push

**Comment by hhslepicka** [comment]
Hole in one? I can't believe it.. 😝

**Comment by klauer** [comment]
🎉

**Comment by teddyrendahl** [comment]
https://gph.is/2cL5I6f

**Comment by teddyrendahl** [comment]
https://media.giphy.com/media/Pc3bbTMINewZq/giphy.gif

**Comment by ZLLentz** [comment]
6 months ago this PR title would have given me a heart attack

**Comment by klauer** [comment]
😆

**Pull request merged**
