### PR TITLE
PERF: set text size on resize event, not on paint event, to avoid 100% cpu

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Move the dynamic text resizing to resize event so it doesn't happen every frame and use the entire cpu

## Motivation and Context

https://jira.slac.stanford.edu/browse/ECS-5143

## How Has This Been Tested?

Interactively to observe the usage
Tests slightly adjusted so they still pass (previously was looking for the paint event)

## Where Has This Been Documented?

Here and in release notes

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive docstrings, including context and API
- [x] New/changed functions and methods are covered in the test suite where possible
- [x] Code has been checked for threading issues (no blocking tasks in GUI thread)
- [x] Test suite passes locally
- [x] Test suite passes on GitHub Actions
- [x] Ran ``docs/pre-release-notes.sh`` and created a pre-release documentation page
- [x] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by ZLLentz** [comment]
This is a draft for now
Robert and I figured this out together
deploying in dev_conda

**Comment by ZLLentz** [comment]
If the tests pass here, then something in #606 is breaking the suite. I have at least one guess already.
If the tests fail here, then there's a more fundamental issue.

**Comment by ZLLentz** [comment]
I guess I'll be taking a stab at an independent "fix atef CI tests" PR. I'll start by comparing package versions.

**Comment by tangkong** [comment]
> I guess I'll be taking a stab at an independent "fix atef CI tests" PR. I'll start by comparing package versions.

Do you mean typhos here?  Or did something about atef die without me knowing?

**Comment by ZLLentz** [comment]
I meant typhos

**Review by tangkong — APPROVED** [review]
LGTM.

**Pull request merged**
