### PR TITLE
DOC: write release notes for v2.4.1

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Bugfixes and maintenance

## Motivation and Context

I want to tag every package that I help maintain since we haven't done this at all in 2023.

## How Has This Been Tested?

n/a

## Where Has This Been Documented?

this is docs

### CODE REVIEW

**Review by tangkong — APPROVED** [review]
Funny how the GHA release notes vary based on who did the migration.

**Review by klauer — APPROVED** [review]

**Comment by ZLLentz** [comment]
In this case, I hand-wrote the notes because there isn't a pre-release docs system in this repo. Should I backpedal and copy/paste the big blurb?

**Comment by klauer** [comment]
I wasn't going to stop the release process for it because the ones listed here are probably _good enough_.

That being said, the more verbose notes I had in the other repos (including the migration PRs) is more descriptive and better representative of the changes (in my opinion)

**Comment by ZLLentz** [comment]
I'll be thorough, there's enough other things that need to happen for the full env release that a few moments here don't really matter.

**Comment by klauer** [comment]
Looks good 👍

**Pull request merged**
